name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v2-beta
      name: Install Go 1.14
      with:
        go-version: 1.14
      id: go
    - uses: actions/checkout@v2
      name: Checkout Code
    - run: |
        go get -v -t -d ./...
      name: Install dependencies
    - run: go test -v ./...
      name: Run Tests
    - run: echo Nothing to build at this time; go build -v .
      name: Build
